codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 2

coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

ignore:
  - "Testing/**"
  - "build/**"
  - "run_tests.sh"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
