name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v4.1
      with:
        cmake-version: '3.22.1'
    
    - name: Install dependencies
      run: sudo apt-get install -y lcov

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests and collect coverage
      run: |
        cmake --build build --target test
        lcov --capture --directory build --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/build/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
